[package]
name = "proposals"
edition = "2021"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.9.9" #{ workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
bytes = { workspace = true }

cycles-minting-canister = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
dfn_candid = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
dfn_core = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
ic-base-types = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
ic-btc-interface = { git = "https://github.com/dfinity/bitcoin-canister", rev="release/2023-08-10" }
ic-crypto-sha2 = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
ic-ic00-types = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
ic-nervous-system-common = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
ic-nervous-system-root = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
ic-nns-constants = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
ic-protobuf = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
registry-canister = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }

# Note: These are compatible with candid 9.x
ic-cdk = "0.11.0"
ic-cdk-macros = "0.8.1"
idl2json = { git = "https://github.com/dfinity/idl2json", rev = "0.9.3" }

[dev-dependencies]
anyhow = "1.0.68"
