[package]
name = "nns-dapp"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
candid = "0.8.4"
futures = "0.3.21"
itertools = "0.10.5"
lazy_static = "1.4.0"
serde = "1.0.171"
serde_bytes = "0.11.7"
serde_cbor = "0.11.2"
serde_json = "1.0.87"
sha2 = "0.10.6"
lzma-rs = "0.2.0"
tar = "0.4.37"
hex = "0.4.3"

# chrono 0.4.19 has vulnerabilities fixed in 0.4.20
# but, 0.4.20 doesn't satisfy ic. We get the followig error when deploying the canister:
# The Replica returned an error: code 5, message: "Wasm module of canister vo5te-2aaaa-aaaaa-aaazq-cai is not valid: Wasm module has an invalid import section. Module imports function '__wbindgen_describe' from '__wbindgen_placeholder__' that is not exported by the runtime."
# 0.4.19 works and satisfies ic.
chrono = "=0.4.19"

ic-cdk = "0.8.1"
ic-cdk-macros = "0.6.10"
cycles-minting-canister = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
dfn_candid = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
dfn_core = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
dfn_protobuf = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
ic-base-types = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
ic-btc-interface = { git = "https://github.com/dfinity/bitcoin-canister", rev="b1693619e3d4dbc00d8c79e9b6886e1db48b21f7" }
ic-certified-map = "0.3.4" # == https://github.com/dfinity/cdk-rs 6a15aa1616bcfdfdc4c120d17d37a089f5700c36
ic-crypto-sha2 = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
ic-ic00-types = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
ic-ledger-core = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
ic-nervous-system-common = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
ic-nervous-system-root = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
ic-nns-common = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
ic-nns-constants = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
ic-nns-governance = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
ic-protobuf = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
ic-sns-swap = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
ic-sns-wasm = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
icp-ledger = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
on_wire = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
registry-canister = { git = "https://github.com/dfinity/ic", rev = "6223a38cfae726e9cc83db9ae27f35ca979dd0d8" }
idl2json = "0.8.7"
flate2 = "1.0.25"
regex = "1.7.1"

[dev-dependencies]
maplit = "1.0.2"
anyhow = "1.0.68"

[features]
# Build flavours; these should not normally be referred to directly in code.
production = ["assets"]
test = ["assets", "toy_data_gen"]
noassets = ["toy_data_gen"]

# Individual features
assets = []
toy_data_gen = []
