# TODO: Remove once the workflow is renamed on GitHub
name: ZZZ old workflow aggregator.yaml
on:
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello world!
